// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: EcobucksPrototypeUI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_BootScreen
void ui_BootScreen_screen_init(void);
lv_obj_t *ui_BootScreen;

// SCREEN: ui_SetupWifiScreen
void ui_SetupWifiScreen_screen_init(void);
lv_obj_t *ui_SetupWifiScreen;
lv_obj_t *ui_SetupWifiLabel;
lv_obj_t *ui_InfoPanel;
lv_obj_t *ui_Dropdown1;
lv_obj_t *ui_TextArea1;
void ui_event_ConnectButton(lv_event_t *e);
lv_obj_t *ui_ConnectButton;
lv_obj_t *ui_ConnectLabel;

// SCREEN: ui_StartScreen
void ui_StartScreen_screen_init(void);
lv_obj_t *ui_StartScreen;
lv_obj_t *ui_WelcomeLabel;
void ui_event_StartButton(lv_event_t *e);
lv_obj_t *ui_StartButton;
lv_obj_t *ui_StartLabel;

// SCREEN: ui_MeasureScreen
void ui_MeasureScreen_screen_init(void);
lv_obj_t *ui_MeasureScreen;
lv_obj_t *ui_WeightInfoPanel;
lv_obj_t *ui_WeighingLabel;
lv_obj_t *ui_WeightLabel;
lv_obj_t *ui_InfoSelectPanel;
lv_obj_t *ui_DisposalTypeSelect;
lv_obj_t *ui_ClaimButton;
lv_obj_t *ui_ClaimLabel;

// SCREEN: ui_QRCodeScreen
void ui_QRCodeScreen_screen_init(void);
lv_obj_t *ui_QRCodeScreen;
lv_obj_t *ui_QRCodePlaceholder;
void ui_event_FinishButton(lv_event_t *e);
lv_obj_t *ui_FinishButton;
lv_obj_t *ui_FinishLabel;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ConnectButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        on_wifi_connect_button_click(e);
    }
}
void ui_event_StartButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_MeasureScreen, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_MeasureScreen_screen_init);
    }
}
void ui_event_FinishButton(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t *target = lv_event_get_target(e);
    if (event_code == LV_EVENT_CLICKED)
    {
        _ui_screen_change(&ui_StartScreen, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_StartScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_BootScreen_screen_init();
    ui_SetupWifiScreen_screen_init();
    ui_StartScreen_screen_init();
    ui_MeasureScreen_screen_init();
    ui_QRCodeScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_BootScreen);
}
