// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
lv_obj_t * ui_SplashScreen;
lv_obj_t * ui_SplashScreenSpinner;


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_FlexContainer;
lv_obj_t * ui_MainScreenLogo;
void ui_event_GoToDisposalRegisterScreenButton(lv_event_t * e);
lv_obj_t * ui_GoToDisposalRegisterScreenButton;
lv_obj_t * ui_GoToDisposalRegisterScreenButtonLabel;
void ui_event_SwipeUpSettings(lv_event_t * e);
lv_obj_t * ui_SwipeUpSettings;


// SCREEN: ui_DisposalRegisterScreen
void ui_DisposalRegisterScreen_screen_init(void);
void ui_event_DisposalRegisterScreen(lv_event_t * e);
lv_obj_t * ui_DisposalRegisterScreen;
lv_obj_t * ui_DisposalRegisterPanel;
lv_obj_t * ui_DisposalRegisterHeader;
void ui_event_DisposalRegisterHeaderBackButton(lv_event_t * e);
lv_obj_t * ui_DisposalRegisterHeaderBackButton;
lv_obj_t * ui_DisposalRegisterHeaderBackButtonIcon;
lv_obj_t * ui_DisposalRegisterHeaderTitle;
lv_obj_t * ui_DisposalRegisterContainer;
lv_obj_t * ui_CurrentWeightLabel;
lv_obj_t * ui_WeightRelativeToMaxWeightBar;
lv_obj_t * ui_LowerBarContainer;
lv_obj_t * ui_WasteTypeDropdown;
void ui_event_RegisterButton(lv_event_t * e);
lv_obj_t * ui_RegisterButton;
lv_obj_t * ui_RegisterButtonLabel;


// SCREEN: ui_QRCodeScreen
void ui_QRCodeScreen_screen_init(void);
lv_obj_t * ui_QRCodeScreen;
lv_obj_t * ui_CreditsLabel;
lv_obj_t * ui_QRCodeContainer;
void ui_event_FinishButton(lv_event_t * e);
lv_obj_t * ui_FinishButton;
lv_obj_t * ui_FinishButtonLabel;


// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
lv_obj_t * ui_SettingsScreen;
lv_obj_t * ui_ConfigurationPanel;
lv_obj_t * ui_SettingsHeader;
void ui_event_SettingsHeaderBackButton(lv_event_t * e);
lv_obj_t * ui_SettingsHeaderBackButton;
lv_obj_t * ui_SettingHeaderBackButtonIcon;
lv_obj_t * ui_SettingsHeaderTitle;
lv_obj_t * ui_SettingsOptionsContainer;
void ui_event_WifiConfigurationButton(lv_event_t * e);
lv_obj_t * ui_WifiConfigurationButton;
lv_obj_t * ui_WifiConfigurationButtonLabel;


// SCREEN: ui_WifiSettingsScreen
void ui_WifiSettingsScreen_screen_init(void);
lv_obj_t * ui_WifiSettingsScreen;
lv_obj_t * ui_WifiConfigurationPanel;
lv_obj_t * ui_Header;
void ui_event_Header_BackButton(lv_event_t * e);
lv_obj_t * ui_WifiSettingsContainer;
lv_obj_t * ui_WifiSSIDContainer;
lv_obj_t * ui_SSIDLabel;
lv_obj_t * ui_SSIDDropdown;
void ui_event_RefreshWifisButton(lv_event_t * e);
lv_obj_t * ui_RefreshWifisButton;
lv_obj_t * ui_RefreshWifisButtonIcon;
lv_obj_t * ui_WifiPasswordContainer;
lv_obj_t * ui_PasswordLabel;
void ui_event_PasswordTextArea(lv_event_t * e);
lv_obj_t * ui_PasswordTextArea;
void ui_event_ConnectToWifiButton(lv_event_t * e);
lv_obj_t * ui_ConnectToWifiButton;
lv_obj_t * ui_ConnectToWifiButtonLabel;
void ui_event_SetupWifiKeyboard(lv_event_t * e);
lv_obj_t * ui_SetupWifiKeyboard;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_942664913[1] = {&ui_img_1471181834};
const lv_img_dsc_t * ui_imgset_849879536[1] = {&ui_img_904781469};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_GoToDisposalRegisterScreenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DisposalRegisterScreen, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_DisposalRegisterScreen_screen_init);
    }
}
void ui_event_SwipeUpSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 250, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_DisposalRegisterScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_register_disposal_to_api(e);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_QRCodeScreen, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_QRCodeScreen_screen_init);
    }
}
void ui_event_DisposalRegisterHeaderBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_RegisterButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DisposalRegisterScreen, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_DisposalRegisterScreen_screen_init);
    }
}
void ui_event_FinishButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DisposalRegisterScreen, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_DisposalRegisterScreen_screen_init);
    }
}
void ui_event_SettingsHeaderBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_WifiConfigurationButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiSettingsScreen, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_WifiSettingsScreen_screen_init);
    }
}
void ui_event_Header_BackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_RefreshWifisButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_refresh_wifi_list(e);
    }
}
void ui_event_PasswordTextArea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_SetupWifiKeyboard,  ui_PasswordTextArea);
        _ui_flag_modify(ui_SetupWifiKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_SetupWifiKeyboard, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_SetupWifiKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_ConnectToWifiButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ui_wifi_setup_connect(e);
    }
}
void ui_event_SetupWifiKeyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        ui_hide_wifi_setup_keyboard(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_SplashScreen_screen_init();
    ui_MainScreen_screen_init();
    ui_DisposalRegisterScreen_screen_init();
    ui_QRCodeScreen_screen_init();
    ui_SettingsScreen_screen_init();
    ui_WifiSettingsScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SplashScreen);
}
