// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
lv_obj_t * ui_SplashScreen;
lv_obj_t * ui_SplashScreenSpinner;


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t * ui_MainScreen;
lv_obj_t * ui_FlexContainer;
lv_obj_t * ui_MainScreenLogo;
void ui_event_GoToDisposalRegisterScreenButton(lv_event_t * e);
lv_obj_t * ui_GoToDisposalRegisterScreenButton;
lv_obj_t * ui_GoToDisposalRegisterScreenButtonLabel;
void ui_event_SwipeUpSettings(lv_event_t * e);
lv_obj_t * ui_SwipeUpSettings;


// SCREEN: ui_DisposalRegisterScreen
void ui_DisposalRegisterScreen_screen_init(void);
lv_obj_t * ui_DisposalRegisterScreen;
lv_obj_t * ui_DisposalRegisterScreenLeftContainer;
lv_obj_t * ui_CurrentWeightTextLabel;
lv_obj_t * ui_CurrentWeightLabel;
lv_obj_t * ui_WeightRelativeToMaxWeightBar;
lv_obj_t * ui_DisposalRegisterScreenRightContainer;
lv_obj_t * ui_AddedDisposalsPanel;
lv_obj_t * ui_NewDisposalButton;
lv_obj_t * ui_Plus;
void ui_event_RegisterDisposalButton(lv_event_t * e);
lv_obj_t * ui_RegisterDisposalButton;
lv_obj_t * ui_RegisterDisposalButtonLabel;


// SCREEN: ui_QRCodeScreen
void ui_QRCodeScreen_screen_init(void);
lv_obj_t * ui_QRCodeScreen;
lv_obj_t * ui_CreditsLabel;
lv_obj_t * ui_QRCodeContainer;
void ui_event_FinishButton(lv_event_t * e);
lv_obj_t * ui_FinishButton;
lv_obj_t * ui_FinishButtonLabel;


// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
lv_obj_t * ui_SettingsScreen;
lv_obj_t * ui_ConfigurationOverlayPanel;
lv_obj_t * ui_SettingsTitleLabel;
lv_obj_t * ui_SettingsOptionsContainer;
void ui_event_WifiConfigurationButton(lv_event_t * e);
lv_obj_t * ui_WifiConfigurationButton;
lv_obj_t * ui_WifiConfigurationButtonLabel;
void ui_event_ExitToMainScreenSymbol(lv_event_t * e);
lv_obj_t * ui_ExitToMainScreenSymbol;


// SCREEN: ui_WifiSettingsScreen
void ui_WifiSettingsScreen_screen_init(void);
lv_obj_t * ui_WifiSettingsScreen;
lv_obj_t * ui_WifiConfigurationPanel;
lv_obj_t * ui_WifiConfigurationTitle;
lv_obj_t * ui_WifiSettingsContainer;
lv_obj_t * ui_WifiSSIDContainer;
lv_obj_t * ui_SSIDLabel;
lv_obj_t * ui_SSIDDropdown;
lv_obj_t * ui_WifiPasswordContainer;
lv_obj_t * ui_PasswordLabel;
lv_obj_t * ui_PasswordTextArea;
void ui_event_ConnectToWifiButton(lv_event_t * e);
lv_obj_t * ui_ConnectToWifiButton;
lv_obj_t * ui_ConnectToWifiButtonLabel;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_GoToDisposalRegisterScreenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DisposalRegisterScreen, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_DisposalRegisterScreen_screen_init);
    }
}
void ui_event_SwipeUpSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 250, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_RegisterDisposalButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_QRCodeScreen, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_QRCodeScreen_screen_init);
    }
}
void ui_event_FinishButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DisposalRegisterScreen, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_DisposalRegisterScreen_screen_init);
    }
}
void ui_event_WifiConfigurationButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiSettingsScreen, LV_SCR_LOAD_ANIM_NONE, 250, 0, &ui_WifiSettingsScreen_screen_init);
    }
}
void ui_event_ExitToMainScreenSymbol(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainScreen, LV_SCR_LOAD_ANIM_MOVE_TOP, 250, 0, &ui_MainScreen_screen_init);
    }
}
void ui_event_ConnectToWifiButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DisposalRegisterScreen, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_DisposalRegisterScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_SplashScreen_screen_init();
    ui_MainScreen_screen_init();
    ui_DisposalRegisterScreen_screen_init();
    ui_QRCodeScreen_screen_init();
    ui_SettingsScreen_screen_init();
    ui_WifiSettingsScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SplashScreen);
}
