// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
extern lv_obj_t * ui_SplashScreen;
extern lv_obj_t * ui_SplashScreenSpinner;
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_FlexContainer;
extern lv_obj_t * ui_MainScreenLogo;
void ui_event_GoToDisposalRegisterScreenButton(lv_event_t * e);
extern lv_obj_t * ui_GoToDisposalRegisterScreenButton;
extern lv_obj_t * ui_GoToDisposalRegisterScreenButtonLabel;
void ui_event_SwipeUpSettings(lv_event_t * e);
extern lv_obj_t * ui_SwipeUpSettings;
// SCREEN: ui_DisposalRegisterScreen
void ui_DisposalRegisterScreen_screen_init(void);
extern lv_obj_t * ui_DisposalRegisterScreen;
extern lv_obj_t * ui_DisposalRegisterScreenLeftContainer;
extern lv_obj_t * ui_CurrentWeightTextLabel;
extern lv_obj_t * ui_CurrentWeightLabel;
extern lv_obj_t * ui_WeightRelativeToMaxWeightBar;
extern lv_obj_t * ui_DisposalRegisterScreenRightContainer;
extern lv_obj_t * ui_AddedDisposalsPanel;
extern lv_obj_t * ui_NewDisposalButton;
extern lv_obj_t * ui_Plus;
void ui_event_RegisterDisposalButton(lv_event_t * e);
extern lv_obj_t * ui_RegisterDisposalButton;
extern lv_obj_t * ui_RegisterDisposalButtonLabel;
// SCREEN: ui_QRCodeScreen
void ui_QRCodeScreen_screen_init(void);
extern lv_obj_t * ui_QRCodeScreen;
extern lv_obj_t * ui_CreditsLabel;
extern lv_obj_t * ui_QRCodeContainer;
void ui_event_FinishButton(lv_event_t * e);
extern lv_obj_t * ui_FinishButton;
extern lv_obj_t * ui_FinishButtonLabel;
// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_ConfigurationOverlayPanel;
extern lv_obj_t * ui_SettingsTitleLabel;
extern lv_obj_t * ui_SettingsOptionsContainer;
void ui_event_WifiConfigurationButton(lv_event_t * e);
extern lv_obj_t * ui_WifiConfigurationButton;
extern lv_obj_t * ui_WifiConfigurationButtonLabel;
void ui_event_ExitToMainScreenSymbol(lv_event_t * e);
extern lv_obj_t * ui_ExitToMainScreenSymbol;
// SCREEN: ui_WifiSettingsScreen
void ui_WifiSettingsScreen_screen_init(void);
extern lv_obj_t * ui_WifiSettingsScreen;
extern lv_obj_t * ui_WifiConfigurationPanel;
extern lv_obj_t * ui_WifiConfigurationTitle;
extern lv_obj_t * ui_WifiSettingsContainer;
extern lv_obj_t * ui_WifiSSIDContainer;
extern lv_obj_t * ui_SSIDLabel;
extern lv_obj_t * ui_SSIDDropdown;
extern lv_obj_t * ui_WifiPasswordContainer;
extern lv_obj_t * ui_PasswordLabel;
extern lv_obj_t * ui_PasswordTextArea;
void ui_event_ConnectToWifiButton(lv_event_t * e);
extern lv_obj_t * ui_ConnectToWifiButton;
extern lv_obj_t * ui_ConnectToWifiButtonLabel;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1456473992);    // assets/Ecobucks-Station-Firmware-Banner.png
LV_IMG_DECLARE(ui_img_ecobuckstextgradient_png);    // assets/EcobucksTextGradient.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
