// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: EcobucksPrototypeUI

#ifndef _ECOBUCKSPROTOTYPEUI_UI_H
#define _ECOBUCKSPROTOTYPEUI_UI_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
    // SCREEN: ui_BootScreen
    void ui_BootScreen_screen_init(void);
    extern lv_obj_t *ui_BootScreen;
    // SCREEN: ui_SetupWifiScreen
    void ui_SetupWifiScreen_screen_init(void);
    extern lv_obj_t *ui_SetupWifiScreen;
    extern lv_obj_t *ui_SetupWifiLabel;
    extern lv_obj_t *ui_InfoPanel;
    extern lv_obj_t *ui_Dropdown1;
    extern lv_obj_t *ui_TextArea1;
    void ui_event_ConnectButton(lv_event_t *e);
    extern lv_obj_t *ui_ConnectButton;
    extern lv_obj_t *ui_ConnectLabel;
    // SCREEN: ui_StartScreen
    void ui_StartScreen_screen_init(void);
    extern lv_obj_t *ui_StartScreen;
    extern lv_obj_t *ui_WelcomeLabel;
    void ui_event_StartButton(lv_event_t *e);
    extern lv_obj_t *ui_StartButton;
    extern lv_obj_t *ui_StartLabel;
    // SCREEN: ui_MeasureScreen
    void ui_MeasureScreen_screen_init(void);
    extern lv_obj_t *ui_MeasureScreen;
    extern lv_obj_t *ui_WeightInfoPanel;
    extern lv_obj_t *ui_WeighingLabel;
    extern lv_obj_t *ui_WeightLabel;
    extern lv_obj_t *ui_InfoSelectPanel;
    extern lv_obj_t *ui_DisposalTypeSelect;
    extern lv_obj_t *ui_ClaimButton;
    extern lv_obj_t *ui_ClaimLabel;
    // SCREEN: ui_QRCodeScreen
    void ui_QRCodeScreen_screen_init(void);
    extern lv_obj_t *ui_QRCodeScreen;
    extern lv_obj_t *ui_QRCodePlaceholder;
    void ui_event_FinishButton(lv_event_t *e);
    extern lv_obj_t *ui_FinishButton;
    extern lv_obj_t *ui_FinishLabel;
    extern lv_obj_t *ui____initial_actions0;

    LV_IMG_DECLARE(ui_img_ecobucks_boot_screen_png); // assets\ecobucks_boot_screen.png

    void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
