// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: EcobucksPrototypeUI

#include "screen/ui/ui.h"

void on_wifi_connect_button_click(lv_event_t *e)
{
	// Your code here
}
