// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: EcobucksPrototypeUI

#include "screen/ui/ui.h"

void ui_BootScreen_screen_init(void)
{
    ui_BootScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BootScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_img_src(ui_BootScreen, &ui_img_ecobucks_boot_screen_png, LV_PART_MAIN | LV_STATE_DEFAULT);
}
