// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_DisposalRegisterScreen_screen_init(void)
{
    ui_DisposalRegisterScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_DisposalRegisterScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DisposalRegisterScreenLeftContainer = lv_obj_create(ui_DisposalRegisterScreen);
    lv_obj_remove_style_all(ui_DisposalRegisterScreenLeftContainer);
    lv_obj_set_width(ui_DisposalRegisterScreenLeftContainer, lv_pct(40));
    lv_obj_set_height(ui_DisposalRegisterScreenLeftContainer, lv_pct(100));
    lv_obj_set_x(ui_DisposalRegisterScreenLeftContainer, -235);
    lv_obj_set_y(ui_DisposalRegisterScreenLeftContainer, 0);
    lv_obj_set_align(ui_DisposalRegisterScreenLeftContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DisposalRegisterScreenLeftContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DisposalRegisterScreenLeftContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DisposalRegisterScreenLeftContainer,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CurrentWeightTextLabel = lv_label_create(ui_DisposalRegisterScreenLeftContainer);
    lv_obj_set_width(ui_CurrentWeightTextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentWeightTextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CurrentWeightTextLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentWeightTextLabel, "Waste Weight");
    lv_obj_set_style_text_font(ui_CurrentWeightTextLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CurrentWeightTextLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CurrentWeightTextLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CurrentWeightTextLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CurrentWeightTextLabel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentWeightLabel = lv_label_create(ui_DisposalRegisterScreenLeftContainer);
    lv_obj_set_width(ui_CurrentWeightLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentWeightLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CurrentWeightLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentWeightLabel, "0kg");
    lv_obj_set_style_text_font(ui_CurrentWeightLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_CurrentWeightLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CurrentWeightLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CurrentWeightLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CurrentWeightLabel, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeightRelativeToMaxWeightBar = lv_bar_create(ui_DisposalRegisterScreenLeftContainer);
    lv_obj_set_height(ui_WeightRelativeToMaxWeightBar, 10);
    lv_obj_set_width(ui_WeightRelativeToMaxWeightBar, lv_pct(40));
    lv_obj_set_align(ui_WeightRelativeToMaxWeightBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_WeightRelativeToMaxWeightBar, lv_color_hex(0xD5FEE4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeightRelativeToMaxWeightBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_WeightRelativeToMaxWeightBar, lv_color_hex(0x000000),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_WeightRelativeToMaxWeightBar, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_WeightRelativeToMaxWeightBar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_WeightRelativeToMaxWeightBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WeightRelativeToMaxWeightBar, lv_color_hex(0x39CE7B),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeightRelativeToMaxWeightBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_DisposalRegisterScreenRightContainer = lv_obj_create(ui_DisposalRegisterScreen);
    lv_obj_remove_style_all(ui_DisposalRegisterScreenRightContainer);
    lv_obj_set_width(ui_DisposalRegisterScreenRightContainer, lv_pct(60));
    lv_obj_set_height(ui_DisposalRegisterScreenRightContainer, lv_pct(100));
    lv_obj_set_x(ui_DisposalRegisterScreenRightContainer, 157);
    lv_obj_set_y(ui_DisposalRegisterScreenRightContainer, 0);
    lv_obj_set_align(ui_DisposalRegisterScreenRightContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DisposalRegisterScreenRightContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DisposalRegisterScreenRightContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DisposalRegisterScreenRightContainer,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_DisposalRegisterScreenRightContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_DisposalRegisterScreenRightContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AddedDisposalsPanel = lv_obj_create(ui_DisposalRegisterScreenRightContainer);
    lv_obj_set_width(ui_AddedDisposalsPanel, 460);
    lv_obj_set_height(ui_AddedDisposalsPanel, 392);
    lv_obj_set_x(ui_AddedDisposalsPanel, 71);
    lv_obj_set_y(ui_AddedDisposalsPanel, 93);
    lv_obj_set_align(ui_AddedDisposalsPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AddedDisposalsPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_AddedDisposalsPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AddedDisposalsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AddedDisposalsPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NewDisposalButton = lv_btn_create(ui_AddedDisposalsPanel);
    lv_obj_set_width(ui_NewDisposalButton, 50);
    lv_obj_set_height(ui_NewDisposalButton, 50);
    lv_obj_set_align(ui_NewDisposalButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NewDisposalButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_NewDisposalButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NewDisposalButton, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NewDisposalButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NewDisposalButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_NewDisposalButton, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_NewDisposalButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_NewDisposalButton, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_NewDisposalButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Plus = lv_label_create(ui_NewDisposalButton);
    lv_obj_set_width(ui_Plus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Plus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Plus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Plus, "+");
    lv_obj_set_style_text_color(ui_Plus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Plus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Plus, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RegisterDisposalButton = lv_btn_create(ui_DisposalRegisterScreenRightContainer);
    lv_obj_set_width(ui_RegisterDisposalButton, 150);
    lv_obj_set_height(ui_RegisterDisposalButton, 50);
    lv_obj_set_x(ui_RegisterDisposalButton, 4);
    lv_obj_set_y(ui_RegisterDisposalButton, 180);
    lv_obj_set_align(ui_RegisterDisposalButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RegisterDisposalButton, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_RegisterDisposalButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_RegisterDisposalButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RegisterDisposalButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RegisterDisposalButton, lv_color_hex(0x2A995B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RegisterDisposalButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_RegisterDisposalButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RegisterDisposalButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RegisterDisposalButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RegisterDisposalButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_RegisterDisposalButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RegisterDisposalButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RegisterDisposalButtonLabel = lv_label_create(ui_RegisterDisposalButton);
    lv_obj_set_width(ui_RegisterDisposalButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RegisterDisposalButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RegisterDisposalButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RegisterDisposalButtonLabel, "Register");
    lv_obj_set_style_text_color(ui_RegisterDisposalButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RegisterDisposalButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RegisterDisposalButtonLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_RegisterDisposalButton, ui_event_RegisterDisposalButton, LV_EVENT_ALL, NULL);

}
