// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: EcobucksPrototypeUI

#include "screen/ui/ui.h"

void ui_MeasureScreen_screen_init(void)
{
    ui_MeasureScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MeasureScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_flex_flow(ui_MeasureScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MeasureScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_WeightInfoPanel = lv_obj_create(ui_MeasureScreen);
    lv_obj_set_width(ui_WeightInfoPanel, lv_pct(100));
    lv_obj_set_height(ui_WeightInfoPanel, lv_pct(70));
    lv_obj_set_x(ui_WeightInfoPanel, 0);
    lv_obj_set_y(ui_WeightInfoPanel, 12);
    lv_obj_set_align(ui_WeightInfoPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WeightInfoPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WeightInfoPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WeightInfoPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_border_color(ui_WeightInfoPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WeightInfoPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_WeightInfoPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_WeightInfoPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeighingLabel = lv_label_create(ui_WeightInfoPanel);
    lv_obj_set_width(ui_WeighingLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_WeighingLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_WeighingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeighingLabel, "You're weighing");
    lv_obj_set_style_text_font(ui_WeighingLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeightLabel = lv_label_create(ui_WeightInfoPanel);
    lv_obj_set_width(ui_WeightLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_WeightLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_WeightLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeightLabel, "0kg");
    lv_obj_set_style_text_font(ui_WeightLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InfoSelectPanel = lv_obj_create(ui_MeasureScreen);
    lv_obj_set_width(ui_InfoSelectPanel, lv_pct(90));
    lv_obj_set_height(ui_InfoSelectPanel, lv_pct(20));
    lv_obj_set_x(ui_InfoSelectPanel, 1);
    lv_obj_set_y(ui_InfoSelectPanel, 44);
    lv_obj_set_align(ui_InfoSelectPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_InfoSelectPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_InfoSelectPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_InfoSelectPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_pad_row(ui_InfoSelectPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_InfoSelectPanel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DisposalTypeSelect = lv_dropdown_create(ui_InfoSelectPanel);
    lv_dropdown_set_options(ui_DisposalTypeSelect, "Recyclable\nSponge\nBattery\nElectronic\n");
    lv_obj_set_height(ui_DisposalTypeSelect, 50);
    lv_obj_set_width(ui_DisposalTypeSelect, lv_pct(50));
    lv_obj_set_align(ui_DisposalTypeSelect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DisposalTypeSelect, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_set_style_text_font(ui_DisposalTypeSelect, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClaimButton = lv_btn_create(ui_InfoSelectPanel);
    lv_obj_set_height(ui_ClaimButton, 50);
    lv_obj_set_width(ui_ClaimButton, lv_pct(40));
    lv_obj_set_align(ui_ClaimButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ClaimButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ClaimButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ClaimButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_ClaimButton, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_ClaimButton, lv_color_hex(0x8BF6BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ClaimButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ClaimLabel = lv_label_create(ui_ClaimButton);
    lv_obj_set_width(ui_ClaimLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_ClaimLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_ClaimLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ClaimLabel, "Claim");
    lv_obj_set_style_text_font(ui_ClaimLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);
}
