// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_QRCodeScreen_screen_init(void)
{
    ui_QRCodeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_QRCodeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_QRCodeScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_QRCodeScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_row(ui_QRCodeScreen, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_QRCodeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CreditsLabel = lv_label_create(ui_QRCodeScreen);
    lv_obj_set_width(ui_CreditsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CreditsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CreditsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CreditsLabel, "+$0");
    lv_obj_set_style_text_font(ui_CreditsLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_QRCodeContainer = lv_obj_create(ui_QRCodeScreen);
    lv_obj_remove_style_all(ui_QRCodeContainer);
    lv_obj_set_width(ui_QRCodeContainer, 200);
    lv_obj_set_height(ui_QRCodeContainer, 200);
    lv_obj_set_align(ui_QRCodeContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_QRCodeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_QRCodeContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_QRCodeContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_QRCodeContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_QRCodeContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FinishButton = lv_btn_create(ui_QRCodeScreen);
    lv_obj_set_width(ui_FinishButton, 150);
    lv_obj_set_height(ui_FinishButton, 50);
    lv_obj_set_align(ui_FinishButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FinishButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_FinishButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_FinishButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FinishButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_FinishButton, lv_color_hex(0x29995A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FinishButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_FinishButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_FinishButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_FinishButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_FinishButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_FinishButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FinishButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FinishButtonLabel = lv_label_create(ui_FinishButton);
    lv_obj_set_width(ui_FinishButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FinishButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_FinishButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FinishButtonLabel, "Finish");
    lv_obj_set_style_text_color(ui_FinishButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FinishButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FinishButtonLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_FinishButton, ui_event_FinishButton, LV_EVENT_ALL, NULL);

}
