// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: EcobucksPrototypeUI

#include "screen/ui/ui.h"

void ui_QRCodeScreen_screen_init(void)
{
    ui_QRCodeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_QRCodeScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_QRCodePlaceholder = lv_img_create(ui_QRCodeScreen);
    lv_obj_set_width(ui_QRCodePlaceholder, 200);
    lv_obj_set_height(ui_QRCodePlaceholder, 200);
    lv_obj_set_align(ui_QRCodePlaceholder, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_QRCodePlaceholder, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_QRCodePlaceholder, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_FinishButton = lv_btn_create(ui_QRCodeScreen);
    lv_obj_set_width(ui_FinishButton, lv_pct(33));
    lv_obj_set_height(ui_FinishButton, lv_pct(11));
    lv_obj_set_x(ui_FinishButton, 0);
    lv_obj_set_y(ui_FinishButton, 183);
    lv_obj_set_align(ui_FinishButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FinishButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_FinishButton, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_FinishButton, lv_color_hex(0x8BF6BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FinishButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FinishLabel = lv_label_create(ui_FinishButton);
    lv_obj_set_width(ui_FinishLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_FinishLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_FinishLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_FinishLabel, "Finish");
    lv_obj_set_style_text_font(ui_FinishLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_FinishButton, ui_event_FinishButton, LV_EVENT_ALL, NULL);
}
