// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: EcobucksPrototypeUI

#include "screen/ui/ui.h"

void ui_StartScreen_screen_init(void)
{
    ui_StartScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StartScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_flex_flow(ui_StartScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_StartScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_row(ui_StartScreen, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_StartScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WelcomeLabel = lv_label_create(ui_StartScreen);
    lv_obj_set_width(ui_WelcomeLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_WelcomeLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_WelcomeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WelcomeLabel, "Welcome!");
    lv_obj_set_style_text_font(ui_WelcomeLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartButton = lv_btn_create(ui_StartScreen);
    lv_obj_set_width(ui_StartButton, lv_pct(33));
    lv_obj_set_height(ui_StartButton, lv_pct(11));
    lv_obj_set_align(ui_StartButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_StartButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_StartButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_StartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_StartButton, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_StartButton, lv_color_hex(0x8BF6BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartLabel = lv_label_create(ui_StartButton);
    lv_obj_set_width(ui_StartLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_StartLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_StartLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartLabel, "Start");
    lv_obj_set_style_text_font(ui_StartLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_StartButton, ui_event_StartButton, LV_EVENT_ALL, NULL);
}
