// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: EcobucksPrototypeUI

#include "screen/ui/ui.h"

void ui_SetupWifiScreen_screen_init(void)
{
    ui_SetupWifiScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SetupWifiScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_flex_flow(ui_SetupWifiScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SetupWifiScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_left(ui_SetupWifiScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SetupWifiScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SetupWifiScreen, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SetupWifiScreen, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SetupWifiScreen, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SetupWifiScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetupWifiLabel = lv_label_create(ui_SetupWifiScreen);
    lv_obj_set_width(ui_SetupWifiLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SetupWifiLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SetupWifiLabel, -11);
    lv_obj_set_y(ui_SetupWifiLabel, 2);
    lv_obj_set_align(ui_SetupWifiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetupWifiLabel, "Setup WiFi.");
    lv_obj_set_style_text_font(ui_SetupWifiLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_InfoPanel = lv_obj_create(ui_SetupWifiScreen);
    lv_obj_set_width(ui_InfoPanel, 600);
    lv_obj_set_height(ui_InfoPanel, 172);
    lv_obj_set_x(ui_InfoPanel, 92);
    lv_obj_set_y(ui_InfoPanel, 8);
    lv_obj_set_align(ui_InfoPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_InfoPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_InfoPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_InfoPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_Dropdown1 = lv_dropdown_create(ui_InfoPanel);
    lv_dropdown_set_options(ui_Dropdown1, "Wifi SSID");
    lv_obj_set_width(ui_Dropdown1, lv_pct(75));
    lv_obj_set_height(ui_Dropdown1, lv_pct(40));
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_set_style_text_font(ui_Dropdown1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_InfoPanel);
    lv_obj_set_width(ui_TextArea1, lv_pct(75));
    lv_obj_set_height(ui_TextArea1, lv_pct(40));
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Password");
    lv_textarea_set_password_mode(ui_TextArea1, true);
    lv_obj_set_style_text_font(ui_TextArea1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectButton = lv_btn_create(ui_SetupWifiScreen);
    lv_obj_set_width(ui_ConnectButton, lv_pct(33));
    lv_obj_set_height(ui_ConnectButton, lv_pct(11));
    lv_obj_set_align(ui_ConnectButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConnectButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ConnectButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_ConnectButton, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_ConnectButton, lv_color_hex(0x8BF6BE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConnectButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectLabel = lv_label_create(ui_ConnectButton);
    lv_obj_set_width(ui_ConnectLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_ConnectLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_ConnectLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectLabel, "Connect");
    lv_obj_set_style_text_color(ui_ConnectLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConnectLabel, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ConnectButton, ui_event_ConnectButton, LV_EVENT_ALL, NULL);
}
