// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SplashScreen_screen_init(void)
{
    ui_SplashScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SplashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_SplashScreen, &ui_img_1456473992, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SplashScreenSpinner = lv_spinner_create(ui_SplashScreen, 1000, 90);
    lv_obj_set_width(ui_SplashScreenSpinner, 40);
    lv_obj_set_height(ui_SplashScreenSpinner, 40);
    lv_obj_set_x(ui_SplashScreenSpinner, 0);
    lv_obj_set_y(ui_SplashScreenSpinner, 120);
    lv_obj_set_align(ui_SplashScreenSpinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SplashScreenSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SplashScreenSpinner, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SplashScreenSpinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_SplashScreenSpinner, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SplashScreenSpinner, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SplashScreenSpinner, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_SplashScreenSpinner, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SplashScreenSpinner, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SplashScreenSpinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SplashScreenSpinner, 6, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_SplashScreenSpinner, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

}
