// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_WifiSettingsScreen_screen_init(void)
{
    ui_WifiSettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WifiSettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiConfigurationPanel = lv_obj_create(ui_WifiSettingsScreen);
    lv_obj_set_width(ui_WifiConfigurationPanel, 760);
    lv_obj_set_height(ui_WifiConfigurationPanel, 440);
    lv_obj_set_align(ui_WifiConfigurationPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiConfigurationPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WifiConfigurationPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiConfigurationPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiConfigurationPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_WifiConfigurationPanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_WifiConfigurationPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiConfigurationTitle = lv_label_create(ui_WifiConfigurationPanel);
    lv_obj_set_width(ui_WifiConfigurationTitle, lv_pct(100));
    lv_obj_set_height(ui_WifiConfigurationTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiConfigurationTitle, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiConfigurationTitle, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_WifiConfigurationTitle, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_WifiConfigurationTitle, "Setup Wi-Fi");
    lv_obj_set_style_text_align(ui_WifiConfigurationTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WifiConfigurationTitle, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiSettingsContainer = lv_obj_create(ui_WifiConfigurationPanel);
    lv_obj_remove_style_all(ui_WifiSettingsContainer);
    lv_obj_set_width(ui_WifiSettingsContainer, lv_pct(100));
    lv_obj_set_height(ui_WifiSettingsContainer, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_WifiSettingsContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiSettingsContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WifiSettingsContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_WifiSettingsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_WifiSettingsContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_WifiSettingsContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiSSIDContainer = lv_obj_create(ui_WifiSettingsContainer);
    lv_obj_remove_style_all(ui_WifiSSIDContainer);
    lv_obj_set_height(ui_WifiSSIDContainer, 50);
    lv_obj_set_width(ui_WifiSSIDContainer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_WifiSSIDContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiSSIDContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_WifiSSIDContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_WifiSSIDContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_WifiSSIDContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_WifiSSIDContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDLabel = lv_label_create(ui_WifiSSIDContainer);
    lv_obj_set_width(ui_SSIDLabel, 200);
    lv_obj_set_height(ui_SSIDLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SSIDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SSIDLabel, "SSID: ");
    lv_obj_set_style_text_font(ui_SSIDLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDDropdown = lv_dropdown_create(ui_WifiSSIDContainer);
    lv_dropdown_set_options(ui_SSIDDropdown, "Select Wi-Fi");
    lv_obj_set_width(ui_SSIDDropdown, 465);
    lv_obj_set_height(ui_SSIDDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SSIDDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SSIDDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags


    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_SSIDDropdown), lv_color_hex(0x29995A),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_SSIDDropdown), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_WifiPasswordContainer = lv_obj_create(ui_WifiSettingsContainer);
    lv_obj_remove_style_all(ui_WifiPasswordContainer);
    lv_obj_set_height(ui_WifiPasswordContainer, 50);
    lv_obj_set_width(ui_WifiPasswordContainer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_WifiPasswordContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiPasswordContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_WifiPasswordContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_WifiPasswordContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_WifiPasswordContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_WifiPasswordContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordLabel = lv_label_create(ui_WifiPasswordContainer);
    lv_obj_set_width(ui_PasswordLabel, 200);
    lv_obj_set_height(ui_PasswordLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PasswordLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PasswordLabel, "Password:");
    lv_obj_set_style_text_font(ui_PasswordLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordTextArea = lv_textarea_create(ui_WifiPasswordContainer);
    lv_obj_set_width(ui_PasswordTextArea, 465);
    lv_obj_set_height(ui_PasswordTextArea, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PasswordTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PasswordTextArea, "Placeholder...");



    ui_ConnectToWifiButton = lv_btn_create(ui_WifiSettingsScreen);
    lv_obj_set_width(ui_ConnectToWifiButton, 150);
    lv_obj_set_height(ui_ConnectToWifiButton, 50);
    lv_obj_set_x(ui_ConnectToWifiButton, 0);
    lv_obj_set_y(ui_ConnectToWifiButton, 169);
    lv_obj_set_align(ui_ConnectToWifiButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConnectToWifiButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ConnectToWifiButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnectToWifiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConnectToWifiButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConnectToWifiButton, lv_color_hex(0x29995A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConnectToWifiButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConnectToWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConnectToWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConnectToWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConnectToWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ConnectToWifiButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectToWifiButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectToWifiButtonLabel = lv_label_create(ui_ConnectToWifiButton);
    lv_obj_set_width(ui_ConnectToWifiButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectToWifiButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConnectToWifiButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectToWifiButtonLabel, "Connect");
    lv_obj_set_style_text_color(ui_ConnectToWifiButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectToWifiButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConnectToWifiButtonLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ConnectToWifiButton, ui_event_ConnectToWifiButton, LV_EVENT_ALL, NULL);

}
