// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

#include <esp_log.h>

#include <e_screen.hpp>

static const char *TAG = "e_ui";

void ui_register_disposal_to_api(lv_event_t * e)
{
	
}

void ui_wifi_setup_connect(lv_event_t * e)
{
	e_screen_wifi_setup_connect();
}

void ui_hide_wifi_setup_keyboard(lv_event_t * e)
{
	lv_obj_t *keyboard = lv_event_get_target(e);
	uint32_t btn_id = lv_keyboard_get_selected_btn(keyboard);
  	const char *txt = lv_keyboard_get_btn_text(keyboard, btn_id);
}

void ui_refresh_wifi_list(lv_event_t * e)
{
	ESP_LOGI(TAG, "Pressed refresh WiFi button.");
	e_rpc_scan_networks_request();
}