// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_comp_BackButton_create_hook(lv_obj_t * comp)
{
}

void ui_comp_BackIcon1_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Header_create_hook(lv_obj_t * comp)
{
}
