// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"


// COMPONENT BackButton

lv_obj_t * ui_BackButton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_BackButton;
    cui_BackButton = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_BackButton, 50);
    lv_obj_set_height(cui_BackButton, 50);
    lv_obj_set_align(cui_BackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_BackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_BackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_BackButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_BackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_BackButton, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_BackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_BackButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_BackIcon;
    cui_BackIcon = lv_img_create(cui_BackButton);
    lv_obj_set_width(cui_BackIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_BackIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_BackIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_BackIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_BackIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BACKBUTTON_NUM);
    children[UI_COMP_BACKBUTTON_BACKBUTTON] = cui_BackButton;
    children[UI_COMP_BACKBUTTON_BACKICON] = cui_BackIcon;
    lv_obj_add_event_cb(cui_BackButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_BackButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_BackButton_create_hook(cui_BackButton);
    return cui_BackButton;
}

