// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_BACKBUTTON_H
#define _UI_COMP_BACKBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT BackButton
#define UI_COMP_BACKBUTTON_BACKBUTTON 0
#define UI_COMP_BACKBUTTON_BACKICON 1
#define _UI_COMP_BACKBUTTON_NUM 2
lv_obj_t * ui_BackButton_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
