// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_WifiSettingsScreen_screen_init(void)
{
    ui_WifiSettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WifiSettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiSettingsPanel = lv_obj_create(ui_WifiSettingsScreen);
    lv_obj_set_width(ui_WifiSettingsPanel, 760);
    lv_obj_set_height(ui_WifiSettingsPanel, 440);
    lv_obj_set_align(ui_WifiSettingsPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiSettingsPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WifiSettingsPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiSettingsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiSettingsPanel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiSettingsPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiSettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiSettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_WifiSettingsPanel, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_WifiSettingsPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiSettingsHeader = lv_obj_create(ui_WifiSettingsPanel);
    lv_obj_remove_style_all(ui_WifiSettingsHeader);
    lv_obj_set_height(ui_WifiSettingsHeader, 50);
    lv_obj_set_width(ui_WifiSettingsHeader, lv_pct(100));
    lv_obj_set_align(ui_WifiSettingsHeader, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiSettingsHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_WifiSettingsHeader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiSettingsHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiSettingsHeaderBackButton = lv_btn_create(ui_WifiSettingsHeader);
    lv_obj_set_width(ui_WifiSettingsHeaderBackButton, 50);
    lv_obj_set_height(ui_WifiSettingsHeaderBackButton, 50);
    lv_obj_set_x(ui_WifiSettingsHeaderBackButton, -335);
    lv_obj_set_y(ui_WifiSettingsHeaderBackButton, 0);
    lv_obj_set_align(ui_WifiSettingsHeaderBackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiSettingsHeaderBackButton, LV_OBJ_FLAG_FLOATING | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiSettingsHeaderBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WifiSettingsHeaderBackButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiSettingsHeaderBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WifiSettingsHeaderBackButton, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WifiSettingsHeaderBackButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiSettingsHeaderBackButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WifiSettingsHeaderBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WifiSettingsHeaderBackButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiSettingsHeaderBackIcon = lv_img_create(ui_WifiSettingsHeaderBackButton);
    lv_img_set_src(ui_WifiSettingsHeaderBackIcon, &ui_img_904781469);
    lv_obj_set_width(ui_WifiSettingsHeaderBackIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiSettingsHeaderBackIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiSettingsHeaderBackIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiSettingsHeaderBackIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiSettingsHeaderBackIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WifiSettingsHeaderBackIcon, 150);

    ui_WifiSettingsHeaderTitle = lv_label_create(ui_WifiSettingsHeader);
    lv_obj_set_width(ui_WifiSettingsHeaderTitle, lv_pct(100));
    lv_obj_set_height(ui_WifiSettingsHeaderTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiSettingsHeaderTitle, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiSettingsHeaderTitle, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_WifiSettingsHeaderTitle, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_label_set_text(ui_WifiSettingsHeaderTitle, "Setup Wi-Fi");
    lv_obj_set_style_text_align(ui_WifiSettingsHeaderTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WifiSettingsHeaderTitle, &ui_font_SyneBold30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiSettingsContainer = lv_obj_create(ui_WifiSettingsPanel);
    lv_obj_remove_style_all(ui_WifiSettingsContainer);
    lv_obj_set_width(ui_WifiSettingsContainer, lv_pct(100));
    lv_obj_set_height(ui_WifiSettingsContainer, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_WifiSettingsContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiSettingsContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WifiSettingsContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_WifiSettingsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_WifiSettingsContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_WifiSettingsContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiSSIDContainer = lv_obj_create(ui_WifiSettingsContainer);
    lv_obj_remove_style_all(ui_WifiSSIDContainer);
    lv_obj_set_height(ui_WifiSSIDContainer, 50);
    lv_obj_set_width(ui_WifiSSIDContainer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_WifiSSIDContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiSSIDContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_WifiSSIDContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_WifiSSIDContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_WifiSSIDContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_WifiSSIDContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDLabel = lv_label_create(ui_WifiSSIDContainer);
    lv_obj_set_width(ui_SSIDLabel, 120);
    lv_obj_set_height(ui_SSIDLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SSIDLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SSIDLabel, "SSID: ");
    lv_obj_set_style_text_font(ui_SSIDLabel, &ui_font_SpaceGroteskMedium24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDDropdown = lv_dropdown_create(ui_WifiSSIDContainer);
    lv_dropdown_set_options(ui_SSIDDropdown, "No networks found.");
    lv_obj_set_width(ui_SSIDDropdown, 510);
    lv_obj_set_height(ui_SSIDDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SSIDDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SSIDDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_SSIDDropdown, &ui_font_SpaceGroteskMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_SSIDDropdown, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_SSIDDropdown), lv_color_hex(0x29995A),
                              LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_SSIDDropdown), 255,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_RefreshWifisButton = lv_btn_create(ui_WifiSSIDContainer);
    lv_obj_set_width(ui_RefreshWifisButton, 44);
    lv_obj_set_height(ui_RefreshWifisButton, 44);
    lv_obj_set_align(ui_RefreshWifisButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RefreshWifisButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RefreshWifisButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RefreshWifisButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RefreshWifisButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RefreshWifisButton, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RefreshWifisButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RefreshWifisButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RefreshWifisButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RefreshWifisButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RefreshWifisButtonIcon = lv_img_create(ui_RefreshWifisButton);
    lv_img_set_src(ui_RefreshWifisButtonIcon, &ui_img_1471181834);
    lv_obj_set_width(ui_RefreshWifisButtonIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RefreshWifisButtonIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RefreshWifisButtonIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RefreshWifisButtonIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RefreshWifisButtonIcon,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_img_set_zoom(ui_RefreshWifisButtonIcon, 100);

    ui_WifiPasswordContainer = lv_obj_create(ui_WifiSettingsContainer);
    lv_obj_remove_style_all(ui_WifiPasswordContainer);
    lv_obj_set_height(ui_WifiPasswordContainer, 50);
    lv_obj_set_width(ui_WifiPasswordContainer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_WifiPasswordContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiPasswordContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_WifiPasswordContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_WifiPasswordContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_WifiPasswordContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_WifiPasswordContainer, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordLabel = lv_label_create(ui_WifiPasswordContainer);
    lv_obj_set_width(ui_PasswordLabel, 120);
    lv_obj_set_height(ui_PasswordLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PasswordLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PasswordLabel, "Password:");
    lv_obj_set_style_text_font(ui_PasswordLabel, &ui_font_SpaceGroteskMedium24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordTextArea = lv_textarea_create(ui_WifiPasswordContainer);
    lv_obj_set_width(ui_PasswordTextArea, 575);
    lv_obj_set_height(ui_PasswordTextArea, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PasswordTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PasswordTextArea, "Password");
    lv_textarea_set_one_line(ui_PasswordTextArea, true);
    lv_textarea_set_password_mode(ui_PasswordTextArea, true);
    lv_obj_clear_flag(ui_PasswordTextArea, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_font(ui_PasswordTextArea, &ui_font_SpaceGroteskMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ConnectToWifiButton = lv_btn_create(ui_WifiSettingsScreen);
    lv_obj_set_width(ui_ConnectToWifiButton, 150);
    lv_obj_set_height(ui_ConnectToWifiButton, 50);
    lv_obj_set_x(ui_ConnectToWifiButton, 0);
    lv_obj_set_y(ui_ConnectToWifiButton, 169);
    lv_obj_set_align(ui_ConnectToWifiButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConnectToWifiButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ConnectToWifiButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnectToWifiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConnectToWifiButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConnectToWifiButton, lv_color_hex(0x39BA7B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConnectToWifiButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ConnectToWifiButton, lv_color_hex(0x5EBA9F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ConnectToWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ConnectToWifiButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ConnectToWifiButton, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ConnectToWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ConnectToWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ConnectToWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ConnectToWifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ConnectToWifiButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectToWifiButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectToWifiButtonLabel = lv_label_create(ui_ConnectToWifiButton);
    lv_obj_set_width(ui_ConnectToWifiButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectToWifiButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConnectToWifiButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectToWifiButtonLabel, "Connect");
    lv_obj_set_style_text_color(ui_ConnectToWifiButtonLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectToWifiButtonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConnectToWifiButtonLabel, &ui_font_SyneSemiBold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetupWifiKeyboard = lv_keyboard_create(ui_WifiSettingsScreen);
    lv_obj_set_width(ui_SetupWifiKeyboard, lv_pct(100));
    lv_obj_set_height(ui_SetupWifiKeyboard, lv_pct(45));
    lv_obj_set_x(ui_SetupWifiKeyboard, 0);
    lv_obj_set_y(ui_SetupWifiKeyboard, 130);
    lv_obj_set_align(ui_SetupWifiKeyboard, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetupWifiKeyboard, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_WifiSettingsHeaderBackButton, ui_event_WifiSettingsHeaderBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RefreshWifisButton, ui_event_RefreshWifisButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PasswordTextArea, ui_event_PasswordTextArea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConnectToWifiButton, ui_event_ConnectToWifiButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetupWifiKeyboard, ui_event_SetupWifiKeyboard, LV_EVENT_ALL, NULL);

}
