// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_HEADER_H
#define _UI_COMP_HEADER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Header
#define UI_COMP_HEADER_HEADER 0
#define UI_COMP_HEADER_BACKBUTTON 1
#define UI_COMP_HEADER_BACKBUTTON_BACKICON 2
#define UI_COMP_HEADER_TITLE 3
#define _UI_COMP_HEADER_NUM 4
lv_obj_t * ui_Header_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
